### ISSUE TITLE
BUG: MLE causes some discord channels to not load until restart (ctrl+r)

### ISSUE THREAD

**Issue by thisismyburner** [Syncxv/vc-message-logger-enhanced#53]
Hello, first of all, thanks for all you guys do on this project, I think it's awesome.

Here's the issue I've been running into for about a month:
Sometimes, switching from one channel to another, randomly, it won't load. It just shows the skeleton screen of messages, and only loads when I ctrl+r. 
![image](https://github.com/user-attachments/assets/b31507b3-9fc9-4ab8-833e-ad113ddab5f5)

Has anyone else had this issue?

**Comment by thisismyburner** [comment]
Note: it also happens without a theme
![image](https://github.com/user-attachments/assets/a6a77d94-ad82-418b-a041-87ff8a083ef9)

**Comment by Syncxv** [comment]
can you send the logs in the console. i cant reproduce this exact issue.
i've fixed the message loading issue here 12eadcf but your deleted and edited messages wont get added back.

**Comment by thisismyburner** [comment]
Sure, I think I can send those. What do you mean about deleted and edited messages?
Thanks!

**Comment by thisismyburner** [comment]
```
Logger.ts:40  Vencord   Webpack  Error: webpack.findByCode found no module
    at _n (webpack.ts:104:17)
    at Li (webpack.ts:358:9)
    at webpack.ts:368:28
    at [vencord.lazy.get] (lazy.ts:98:47)
    at au.<computed> [as apply] (lazy.ts:56:65)
    at Object.addToLog (index.tsx:376:23)
    at Object.applyKeywordEntries (index.tsx:364:22)
    at Object.modify (index.tsx:451:22)
    at h._dispatch (WebpackModule613568:2:2257)
    at eval (WebpackModule613568:2:1980) Filter: 
Array(1)
lazy.ts:56 Uncaught (in promise) TypeError: Function.prototype.apply was called on null, which is null and not a function
    at au.<computed> [as apply] (lazy.ts:56:50)
    at Object.addToLog (index.tsx:376:23)
    at Object.applyKeywordEntries (index.tsx:364:22)
    at Object.modify (index.tsx:451:22)
    at h._dispatch (WebpackModule613568:2:2257)
    at eval (WebpackModule613568:2:1980)
    at l.log (web.fb719e6….js:12:9593310)
    at h._dispatchWithLogging (WebpackModule613568:2:1922)
    at h._dispatchWithDevtools (WebpackModule613568:2:1498)
    at Object.dispatch_LOAD_MESSAGES_SUCCESS [as LOAD_MESSAGES_SUCCESS] (WebpackModule613568:2:812)
index.tsx:373 Uncaught (in promise) TypeError: o is not iterable
    at index.tsx:373:48
web.fb719e6….js:12 [Routing/Utils] transitionTo - Transitioning to /channels/[REDACTED]/[REDACTED]
web.fb719e6….js:12 [RPCServer:IPC] Socket Message: 9 
Object
web.fb719e6….js:12 [RPCServer:IPC] Socket Emit: 9 
Object
web.fb719e6….js:12 [MessageActionCreators] Fetching messages for [REDACTED] between undefined and undefined. jump={"jumpType":"ANIMATED"}
db.ts:141 No messages found in range
web.fb719e6….js:12 [MessageActionCreators] Fetched 5 messages for [REDACTED] isBefore:false isAfter:false
web.fb719e6….js:12 [ChannelMessages] loadComplete: resetting state for channelId=[REDACTED], sending.length=0
web.fb719e6….js:12 [RPCServer:IPC] Socket Message: 9 
Object
web.fb719e6….js:12 [RPCServer:IPC] Socket Message: 9 
Object
web.fb719e6….js:12 [RPCServer:IPC] Socket Emit: 9 
Object
web.fb719e6….js:12 [RPCServer:IPC] Socket Emit: 9 
Object
web.fb719e6….js:12 [RPCServer:IPC] Socket Emit: 9 
Object
web.fb719e6….js:12 [MessageActionCreators] Fetching messages for [REDACTED] between undefined and undefined. jump={"jumpType":"ANIMATED"}
web.fb719e6….js:12 [Routing/Utils] transitionTo - Transitioning to /channels/[REDACTED]/[REDACTED]
db.ts:141 No messages found in range
web.fb719e6….js:12 [MessageActionCreators] Fetched 50 messages for [REDACTED] isBefore:false isAfter:false
web.fb719e6….js:12 [ChannelMessages] loadComplete: resetting state for channelId=[REDACTED], sending.length=0
web.fb719e6….js:12 [MessageActionCreators] Fetching messages for [REDACTED] between undefined and undefined. jump={"jumpType":"ANIMATED"}
web.fb719e6….js:12 [Routing/Utils] transitionTo - Transitioning to /channels/[REDACTED]/[REDACTED]
db.ts:141 No messages found in range
web.fb719e6….js:12 [MessageActionCreators] Fetched 50 messages for [REDACTED] isBefore:false isAfter:false
web.fb719e6….js:12 [ChannelMessages] loadComplete: resetting state for channelId=[REDACTED], sending.length=0
web.fb719e6….js:12 [MessageActionCreators] Fetching messages for [REDACTED] between undefined and undefined. jump={"jumpType":"ANIMATED"}
web.fb719e6….js:12 [Routing/Utils] transitionTo - Transitioning to /channels/[REDACTED]/[REDACTED]
db.ts:141 No messages found in range
web.fb719e6….js:12 [MessageActionCreators] Fetched 50 messages for [REDACTED] isBefore:false isAfter:false
web.fb719e6….js:12 [ChannelMessages] loadComplete: resetting state for channelId=[REDACTED], sending.length=0
web.fb719e6….js:12 [Routing/Utils] transitionTo - Transitioning to /channels/[REDACTED]/[REDACTED]
web.fb719e6….js:12 [MessageActionCreators] Fetching messages for [REDACTED] between undefined and undefined. jump={"jumpType":"ANIMATED"}
web.fb719e6….js:12 [Routing/Utils] transitionTo - Transitioning to /channels/[REDACTED]/[REDACTED]
db.ts:141 No messages found in range
web.fb719e6….js:12 [MessageActionCreators] Fetched 50 messages for [REDACTED] isBefore:false isAfter:false
Logger.ts:40  Vencord   Webpack  Error: webpack.findByCode found no module
    at _n (webpack.ts:104:17)
    at Li (webpack.ts:358:9)
    at webpack.ts:368:28
    at [vencord.lazy.get] (lazy.ts:98:47)
    at au.<computed> [as apply] (lazy.ts:56:65)
    at Object.addToLog (index.tsx:376:23)
    at Object.applyKeywordEntries (index.tsx:364:22)
    at Object.modify (index.tsx:451:22)
    at h._dispatch (WebpackModule613568:2:2257)
    at eval (WebpackModule613568:2:1980) Filter: 
Array(1)
_log	@	Logger.ts:40
lazy.ts:56 Uncaught (in promise) TypeError: Function.prototype.apply was called on null, which is null and not a function
    at au.<computed> [as apply] (lazy.ts:56:50)
    at Object.addToLog (index.tsx:376:23)
    at Object.applyKeywordEntries (index.tsx:364:22)
    at Object.modify (index.tsx:451:22)
    at h._dispatch (WebpackModule613568:2:2257)
    at eval (WebpackModule613568:2:1980)
    at l.log (web.fb719e6….js:12:9593310)
    at h._dispatchWithLogging (WebpackModule613568:2:1922)
    at h._dispatchWithDevtools (WebpackModule613568:2:1498)
    at Object.dispatch_LOAD_MESSAGES_SUCCESS [as LOAD_MESSAGES_SUCCESS] (WebpackModule613568:2:812)
index.tsx:373 Uncaught (in promise) TypeError: o is not iterable
    at index.tsx:373:48
```

**Comment by Syncxv** [comment]
i guess you have an old version of the plugin, or some other plugin is having conflict with this one. 
can you check if you're on the latest version

![image](https://github.com/user-attachments/assets/dd32b717-0d5d-4cf6-9ac2-f926e14dda11)

**Comment by thisismyburner** [comment]
![image](https://github.com/user-attachments/assets/6590216e-24c0-481a-acb3-8c5ee3f81aa4)

**Comment by thisismyburner** [comment]
Hey, any update on this @Syncxv?
