### ISSUE TITLE
[Bug] save image to disk make Vesktop white screen

### ISSUE THREAD

**Issue by c0re100** [Syncxv/vc-message-logger-enhanced#9]
Not sure why it happen...🤔
electron remote is null.
![image](https://github.com/Syncxv/vc-message-logger-enhanced/assets/5726473/eead0d06-386a-402c-8e26-1a69deba0cf7)
I guess it's related to Vesktop itself.

```
bf6291f70b6742f944.js:1 TypeError: Cannot read properties of undefined (reading 'getCurrentWindow')
    at b75dadc302bf014648ec.js:1:15675
    at O.componentDidMount (b75dadc302bf014648ec.js:1:15829)
    at iX (00bf6291f70b6742f944.js:1:818762)
    at e (00bf6291f70b6742f944.js:1:839315)
    at 00bf6291f70b6742f944.js:1:839326
    at sR (00bf6291f70b6742f944.js:1:839838)
    at sD (00bf6291f70b6742f944.js:1:823208)
    at L (00bf6291f70b6742f944.js:1:893082)
    at O (00bf6291f70b6742f944.js:1:893612)
    at 00bf6291f70b6742f944.js:1:897093
    ```

**Comment by Syncxv** [comment]
hmm thats interesting.
update the plugin and see if it still crashes

**Comment by Syncxv** [comment]
should be fixed now

[2f4213d](https://github.com/Syncxv/vc-message-logger-enhanced/commit/2f4213d2e85269c8324d1dba901e7a3f79f533ad)

**Comment by c0re100** [comment]
> should be fixed now
> 
> [2f4213d](https://github.com/Syncxv/vc-message-logger-enhanced/commit/2f4213d2e85269c8324d1dba901e7a3f79f533ad)

Yes, it works.
But browse and open image cache folder button are broken by DiscordNative too.
